# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "my-node-app"
client_id = "711a7ad35e19818e6ad48162ca453eac"
application_url = "https://coffee-maldives-printer-loaded.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://coffee-maldives-printer-loaded.trycloudflare.com/auth/callback",
  "https://coffee-maldives-printer-loaded.trycloudflare.com/auth/shopify/callback",
  "https://coffee-maldives-printer-loaded.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "it-path-dev-store.myshopify.com"
