# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Contact Form with API"
client_id = "a9d2d3ce1a58b9f61f3189ab41b41dcb"
application_url = "https://medicare-alumni-contained-salvation.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://medicare-alumni-contained-salvation.trycloudflare.com/auth/callback",
  "https://medicare-alumni-contained-salvation.trycloudflare.com/auth/shopify/callback",
  "https://medicare-alumni-contained-salvation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "anavya-store.myshopify.com"
