# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "my-node-app"
client_id = "4cf99c146a1a44aec551a47c474d5078"
application_url = "https://myers-compliance-injured-promise.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://myers-compliance-injured-promise.trycloudflare.com/auth/callback",
  "https://myers-compliance-injured-promise.trycloudflare.com/auth/shopify/callback",
  "https://myers-compliance-injured-promise.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "it-path-dev-store.myshopify.com"
