# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Contact form to any api"
client_id = "763f8082fff2f80f70d9b6766f654c10"
application_url = "https://shopify-form-builder-gcmn.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shopify-form-builder-gcmn.vercel.app/auth/callback",
  "https://shopify-form-builder-gcmn.vercel.app/auth/shopify/callback",
  "https://shopify-form-builder-gcmn.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "it-path-dev-store.myshopify.com"
