# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Contact form to any API"
client_id = "c4351fdf89a0ae86be14e8815039a599"
application_url = "https://mountains-trial-eligibility-bold.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mountains-trial-eligibility-bold.trycloudflare.com/auth/callback",
  "https://mountains-trial-eligibility-bold.trycloudflare.com/auth/shopify/callback",
  "https://mountains-trial-eligibility-bold.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "it-path-dev-store.myshopify.com"
