# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "form-builder"
client_id = "b1dde03422dce735642fb2d448471911"
application_url = "https://plans-beliefs-automation-fields.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://plans-beliefs-automation-fields.trycloudflare.com/auth/callback",
  "https://plans-beliefs-automation-fields.trycloudflare.com/auth/shopify/callback",
  "https://plans-beliefs-automation-fields.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "it-path-dev-store.myshopify.com"
