# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "my-node-app"
client_id = "bc655ee29ec527170f5df4937c23e237"
application_url = "https://ct-urban-utah-ser.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ct-urban-utah-ser.trycloudflare.com/auth/callback",
  "https://ct-urban-utah-ser.trycloudflare.com/auth/shopify/callback",
  "https://ct-urban-utah-ser.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-32f3d426.myshopify.com"
