# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Contact form with API"
client_id = "43d21ded3ed874907af1c40c209c3a81"
application_url = "https://employer-lauderdale-angel-comparisons.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://employer-lauderdale-angel-comparisons.trycloudflare.com/auth/callback",
  "https://employer-lauderdale-angel-comparisons.trycloudflare.com/auth/shopify/callback",
  "https://employer-lauderdale-angel-comparisons.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "it-path-dev-store.myshopify.com"
